### ISSUE TITLE
Bug in minimum curvature method

### ISSUE THREAD

**Issue by JoshRosenstein** [bpamos/directional-survey-converter#9]
Hello, was just poking around and saw within your minimum curvature method , your beta has a small parentheses issue. 

https://github.com/bpamos/welltrajconvert/blob/f1976dd4ae2656877da76de37b5689f5c3d45d82/welltrajconvert/wellbore_trajectory.py#L130-L134

```py
beta = np.arccos(
    np.cos(inc_rad - inc_rad_shift)
    - (np.sin(inc_rad_shift) * np.sin(inc_rad) * (1 - np.cos(azim_rad - azim_rad_shift)))
)
```

**Comment by bpamos** [comment]
Nice catch. It has been corrected.
